version: "2"

volumes:
  config:
  mosquitto:
  balena-rules-editor-data:
  pulse:
  syncthingconfig:
  serverfiles:
  servercache:

networks:
  default:
  proxy:
    external: true

services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - default
    labels:
      io.balena.features.supervisor-api: "1"
    depends_on:
      - rules-editor

  rules-editor:
    build: ./rules-editor
    container_name: rules-editor
    volumes:
      - "balena-rules-editor-data:/var/lib/rules-editor/"
    privileged: true
    ports:
      - "3000:3000"
    networks:
      - default
    labels:
      io.balena.features.supervisor-api: "1"
    depends_on:
      - rhasspy
      - homeassistant
      - hass-configurator

  # audio:
  #   build: ./audio
  #   privileged: true
  #   volumes:
  #     - "pulse:/run/pulse"
  #   environment:
  #     - AUDIO_LOG_LEVEL=DEBUG

  rhasspy:
    build: ./rhasspy
    container_name: rhasspy
    ports:
      - "12101:12101"
    expose:
      - "12101"
    command: --profile en --user-profiles /profiles
    networks:
      - default
    volumes:
      - "pulse:/run/pulse"
    environment:
      - PULSE_SERVER=unix:/run/pulse/pulseaudio.socket
    depends_on:
      - mqtt

  homeassistant:
    build: homeassistant
    container_name: homeassistant
    ports:
      - "8123:8123"
    privileged: true
    volumes:
      - "config:/config"
    restart: always

  mqtt:
    build: mqtt
    container_name: mqtt
    ports:
      - 1883:1883
      - 9001:9001
    restart: always
    volumes:
      - mosquitto:/mosquitto/data

  hass-configurator:
    image: "causticlab/hass-configurator-docker:latest"
    restart: always
    container_name: hass-configurator
    ports:
      - "3218:3218"
    volumes:
      - "config:/hass-config"
    environment:
      - HC_BASEPATH=/hass-config

  syncthing:
    image: linuxserver/syncthing
    container_name: syncthing
    environment:
      - PUID=1000 # for UserID
      - PGID=1000 # for GroupID
      - UMASK_SET=<022>
    volumes:
      - syncthingconfig:/config
      - config:/home-assistant-config
      - mosquitto:/mosquitto
      - balena-rules-editor-data:/balena-rules-editor-data
      - pulse:/pulse
      - serverfiles:/minecraft-serverfiles
      - servercache:/servercache
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    restart: unless-stopped

  mc-server:
    network_mode: host
    restart: always
    build: ./mc-server
    privileged: true
    labels:
      io.balena.features.dbus: 1
      io.balena.features.supervisor-api: 1
    volumes:
      - serverfiles:/usr/src/serverfiles
      - servercache:/servercache
    ports:
      - "25565:25565/tcp"
      - "25575:25575/tcp"
  scp-server:
    network_mode: host
    restart: always
    build: ./scp-server
    privileged: false
    labels:
      io.balena.features.dbus: 1
    volumes:
      - serverfiles:/serverfiles
      - servercache:/servercache
    ports:
      - "22:22/udp"
      - "22:22/tcp"
  balena-rcon:
    network_mode: host
    restart: always
    build: ./balena-rcon
    privileged: true
    ports:
      - "25575:25575/tcp"
