version: '2'

volumes:
  config:
  mosquitto:
  balena-rules-editor-data:
  pulse:

networks:
  default:
  proxy:
    external: true

services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - '80:80'
    networks:
      - default
    labels:
      io.balena.features.supervisor-api: '1'
    depends_on:
      - rules-editor

  rules-editor:
    build: ./rules-editor
    container_name: rules-editor
    volumes:
      - 'balena-rules-editor-data:/var/lib/rules-editor/'
    ports:
      - '3000:3000'
    networks:
      - default
    labels:
      io.balena.features.supervisor-api: '1'
    depends_on:
      - rhasspy
      - homeassistant
      - mqtt
      - hass-configurator

  audio:
    image: bh.cr/balenablocks/audio-amd64
    privileged: true
    volumes:
      - 'pulse:/run/pulse'
    environment:
      - AUDIO_LOG_LEVEL=DEBUG

  rhasspy:
    build: ./rhasspy
    container_name: rhasspy
    ports:
      - '12101:12101'
    expose:
      - '12101'
    command: --profile en --user-profiles /profiles
    networks:
      - default
    volumes:
      - 'pulse:/run/pulse'
    environment:
      - PULSE_SERVER=unix:/run/pulse/pulseaudio.socket

  homeassistant:
    build: homeassistant
    ports:
      - '8123:8123'
    privileged: true
    volumes:
      - 'config:/config'
    restart: always

  mqtt:
    build: mqtt
    ports:
      - 1883:1883
      - 9001:9001
    restart: always
    volumes:
      - mosquitto:/mosquitto/data

  hass-configurator:
    image: 'causticlab/hass-configurator-docker:latest'
    restart: always
    ports:
      - '3218:3218'
    volumes:
      - 'config:/hass-config'
    environment:
      - HC_BASEPATH=/hass-config
